# Generated by Django 5.2.17 on 2026-09-29 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('free', '무료 회원'), ('paid', '유료 회원'), ('beta', '베타 테스터'), ('staff', '직원'), ('gift', '한 세트'), ('admin', '관리자')], default='free', max_length=8, verbose_name='등급')),
                ('full_access', models.BooleanField(default=False, verbose_name='전체 기능')),
                ('models_provided', models.BooleanField(default=False, verbose_name='Crema 모델 제공')),
                ('model_budget_krw', models.PositiveIntegerField(default=0, verbose_name='월 모델 한도(원)')),
                ('expires_at', models.DateTimeField(blank=True, help_text='비우면 계속. 지나면 무료 회원으로 씁니다.', null=True, verbose_name='끝나는 때')),
                ('suspended_at', models.DateTimeField(blank=True, help_text='정지하면 앱 로그인이 모두 끊깁니다.', null=True, verbose_name='정지한 때')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '회원 등급',
                'verbose_name_plural': '회원 등급',
            },
        ),
    ]
