# Generated by Django 5.2.17 on 2026-09-29 16:05

import django.db.models.deletion
import web.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(default=web.models.new_invite_code, max_length=40, unique=True, verbose_name='코드')),
                ('grade', models.CharField(choices=[('free', '무료 회원'), ('paid', '유료 회원'), ('beta', '베타 테스터'), ('staff', '직원'), ('gift', '한 세트'), ('admin', '관리자')], default='gift', max_length=8, verbose_name='줄 등급')),
                ('days', models.PositiveIntegerField(blank=True, default=90, help_text='받은 날부터. 비우면 계속.', null=True, verbose_name='기간(일)')),
                ('models_provided', models.BooleanField(blank=True, help_text='비우면 등급 기본값', null=True, verbose_name='Crema 모델 제공')),
                ('model_budget_krw', models.PositiveIntegerField(blank=True, help_text='비우면 등급 기본값', null=True, verbose_name='월 모델 한도(원)')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='최대 인원')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='링크 유효 기한')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='누구·어떤 홍보')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '초대 링크',
                'verbose_name_plural': '초대 링크',
            },
        ),
        migrations.CreateModel(
            name='InviteUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='web.invite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_uses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('invite', 'user')},
            },
        ),
    ]
