# Generated by Django 5.2.17 on 2026-10-01 08:51

import django.db.models.deletion
import django.utils.timezone
import web.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_membership_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Crema 이용권', 'verbose_name_plural': 'Crema 이용권'},
        ),
        migrations.RemoveField(
            model_name='membership',
            name='full_access',
        ),
        migrations.AddField(
            model_name='membership',
            name='cycle',
            field=models.CharField(choices=[('once', '전체 기간'), ('monthly', '시작일 기준 매월')], default='monthly', max_length=8, verbose_name='갱신'),
        ),
        migrations.AddField(
            model_name='membership',
            name='key_limit_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, verbose_name='월 교정 비용 한도 (USD)'),
        ),
        migrations.AddField(
            model_name='membership',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='시작'),
        ),
        migrations.AddField(
            model_name='membership',
            name='voice_allowance_ms',
            field=models.PositiveBigIntegerField(default=7200000, help_text='60분 = 3,600,000 / 120분 = 7,200,000', verbose_name='기간당 음성 시간 (밀리초)'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='비우면 계속. 지나면 무료로 씁니다.', null=True, verbose_name='끝나는 때'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='kind',
            field=models.CharField(choices=[('free', '무료'), ('trial', '무료 체험'), ('standard', '4,900원 이용권'), ('plus', '9,900원 이용권'), ('beta', '무료 베타'), ('partner', '파트너 무료'), ('employee', '직원 무료'), ('owner', '소유자·관리자')], default='trial', max_length=8, verbose_name='종류'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='부여·변경 사유'),
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=web.models.new_invite_code, editable=False, max_length=16, unique=True, verbose_name='코드')),
                ('kind', models.CharField(choices=[('beta', '무료 베타'), ('partner', '파트너 무료'), ('employee', '직원 무료')], default='partner', max_length=8, verbose_name='종류')),
                ('days', models.PositiveIntegerField(blank=True, help_text='받은 날부터. 비우면 계속.', null=True, verbose_name='기간(일)')),
                ('models_provided', models.BooleanField(blank=True, help_text='비우면 종류 기본값', null=True, verbose_name='Crema 모델 제공')),
                ('model_budget_krw', models.PositiveIntegerField(blank=True, help_text='비우면 종류 기본값', null=True, verbose_name='월 모델 한도(원)')),
                ('note', models.CharField(max_length=200, verbose_name='받는 사람 메모')),
                ('expires_at', models.DateTimeField(verbose_name='사용 기한')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='쓴 때')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='쓴 사람')),
            ],
            options={
                'verbose_name': '초대 코드',
                'verbose_name_plural': '초대 코드',
            },
        ),
        migrations.DeleteModel(
            name='InviteUse',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
