# Generated by Django 5.2.17 on 2026-10-01 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_access_and_invite_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, unique=True)),
                ('spent_krw', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('reserved_krw', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=128, unique=True)),
                ('limit_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('usage_usd', models.DecimalField(decimal_places=10, default=0, max_digits=18)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('access', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.membership')),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_keys', to='web.apptoken')),
            ],
        ),
        migrations.CreateModel(
            name='ReportConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('notice', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_report_consent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('issuing', 'issuing'), ('issued', 'issued'), ('reported', 'reported'), ('settled', 'settled'), ('failed', 'failed')], default='issuing', max_length=12)),
                ('authorized_ms', models.PositiveBigIntegerField()),
                ('reserved_ms', models.PositiveBigIntegerField()),
                ('charged_ms', models.PositiveBigIntegerField(null=True)),
                ('reported_ms', models.PositiveBigIntegerField(null=True)),
                ('audio_ms', models.PositiveBigIntegerField(null=True)),
                ('outcome', models.CharField(blank=True, max_length=24)),
                ('input_mode', models.CharField(blank=True, max_length=12)),
                ('stt_ms', models.PositiveIntegerField(null=True)),
                ('total_ms', models.PositiveIntegerField(null=True)),
                ('provider_id', models.CharField(blank=True, max_length=160)),
                ('cost_usd', models.DecimalField(decimal_places=10, max_digits=18, null=True)),
                ('reserve_krw', models.DecimalField(decimal_places=6, max_digits=18)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('settled_at', models.DateTimeField(null=True)),
                ('access', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.membership')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.spendperiod')),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.apptoken')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=16)),
                ('stage', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=48)),
                ('app_version', models.CharField(max_length=24)),
                ('os', models.CharField(blank=True, max_length=48)),
                ('target_app', models.CharField(blank=True, max_length=64)),
                ('field_class', models.CharField(blank=True, max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_errors', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.voicesession')),
            ],
        ),
        migrations.AddIndex(
            model_name='voicesession',
            index=models.Index(fields=['state', 'created_at'], name='web_voicese_state_9961c9_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesession',
            index=models.Index(fields=['access', 'period_start'], name='web_voicese_access__f98a3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='voicesession',
            constraint=models.UniqueConstraint(fields=('access', 'request_id'), name='unique_voice_request'),
        ),
    ]
